import java.util.LinkedList;

class MyQueue<T> extends LinkedList<T> {
	private static final long serialVersionUID = 1L; //Generated by Eclipse
	private int maxLength;

	MyQueue(int length) {
		maxLength = length;
	}

	public void enqueue(T item) throws Exception {
		if(this.size() == maxLength)
			throw new Exception("Full");

		this.add(item);
		
	}

	public T dequeue() throws Exception {
		T item;
		
		if(this.size() == 0)
			throw new Exception("Empty");

		item = this.getFirst();
		this.removeFirst();
		
		return item;

	}

	public boolean isFull() {
		return this.size() == maxLength;
	}
	
	@Override
	public boolean isEmpty() {
		return this.size() == 0;
	}

	@Override
	public String toString() {
		StringBuilder returnVal = new StringBuilder();

		for (T s : this) {
			returnVal.append(s.toString());
			returnVal.append(", ");
		}

		returnVal.delete(returnVal.length() - 2, returnVal.length());

		return returnVal.toString();
	}
	
}